from enum import Enum


class EventTypes(Enum):
    CONNECT_CONTROLLER = 1
    SET_AUTOMOBILE_ROUTE_STATE = 2
    SET_CYCLIST_ROUTE_STATE = 3
    SET_PEDESTRIAN_ROUTE_STATE = 4
    SET_BOAT_ROUTE_STATE = 5
    SET_BRIDGE_WARNING_STATE = 6
    REQUEST_BRIDGE_STATE = 7
    REQUEST_BARRIERS_STATE = 8
    REQUEST_BRIDGE_ROAD_EMPTY = 9
    REQUEST_BRIDGE_WATER_EMPTY = 10
    ACKNOWLEDGE_BRIDGE_STATE = 11
    ERROR_UNKNOWN_EVENT_TYPE = 12
    ERROR_MALFORMED_MESSAGE = 13
    ERROR_INVALID_STATE = 14
    ERROR_NOT_PARSEABLE = 15
    SESSION_START = 16
    ENTITY_ENTERED_ZONE = 17
    ENTITY_EXITED_ZONE = 18
